### ISSUE TITLE
Feature: User can view information about a player and their game stats.

### ISSUE THREAD

**Issue by eric-k-chu** [eric-k-chu/Castle#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to search for a player and get information about the player.

## 📐 Functionality

When a user searches for a player, a page will load containing information about the player's account and in-game stats.

## 🖼️ Wireframes

Mobile

Home Page Search
![Home Page](https://github.com/eric-k-chu/ajax-project/assets/47008060/07b9c78d-b10d-4f07-8b07-606e0cf9a84b)

Search Failed
![Search failed](https://github.com/eric-k-chu/ajax-project/assets/47008060/dc7821e4-5d42-46a8-83e9-3988cbf2e502)

Successful Search
![Player Info and Stats(1)](https://github.com/eric-k-chu/ajax-project/assets/47008060/4446b233-2c57-4a0e-935e-4888bf985a5d)

Desktop

Home Page Search
![Desktop - Home Page](https://github.com/eric-k-chu/ajax-project/assets/47008060/90ef59ce-4b55-48e9-a96d-658398b7af49)

Search Failed
![Desktop - Search failed](https://github.com/eric-k-chu/ajax-project/assets/47008060/7b458c0d-e267-4c9e-8f53-892535c75ef2)

Successful Search
![Desktop - Player Info and Stats(1)](https://github.com/eric-k-chu/ajax-project/assets/47008060/1be2904d-47ec-4dc5-8b52-aa2d8f097d1d)

## ✅ Task List
- [x] Add a link tag in the `<header>` section of your HTML page that refers to the font-awesome icons.
- [x] Add another link tag in the `<header>` section of your HTML page for the JetBrains Mono font.
- [x] Add another link tag in the  `<header>` section of your HTML page for [flag-icons](https://github.com/lipis/flag-icons)
- [x] Write CSS for mobile devices first.
- [x] Adjust styling to fluidly adapt to desktop.
- [x] Create the HTML for the `header-container` so that it matches the figma example. The fa icon used is the regular `chess-rook`. 
- [x] Below the header, create the HTML for the `nav-bar` so that it matches the figma example. Create an `<a>` for the `Leaderboards` page.
- [x] Create the rest of the HTML for the home page. The fa icon in the middle of the page is the `chess` icon.
- [x] Adjust styling to fluidly adapt to desktop.
- [x] Create the HTML for the `search-result-failed` page. The fa icon in the middle of the page is `person-circle-question' icon.
- [x] Create the HTML for the `player-info` page. 
  - [x] The top section should be named 'account-info'.
  - [x] The section below `account-info` should be the following.
    - [x] The top left section should be named `league-rank`.
    - [x] The middle left section should be named `stats`.
    - [x] The bottom left section should be named `clubs`.
    - [x] The right section should be named `game-archives`.  
- [x] Add an `input` event listener for the search input in the `header-container` and in the `home-page`. They should retrieve the value inputted by the user and make an XHR to the player profile endpoint `https://api.chess.com/pub/player/$input_value`.
  - [x] If the result of the XHR status is not 200, then view swap to the `search-result-failed` page.
  - [x] If the result of the XHR status is 200, then view swap to the `player-info` page. Then create and call the following functions.
    - [x] Create a function called `insertAccountInfo` with a single parameter `response`. This sets the textContent of all the `account-info` HTML to the `xhr.reponse` properties.
    - [x] Call `insertAccountInfo` and pass in `xhr.response` from the player profile endpoint.
    - [x] Create a function called `renderStats` with two parameters `type` and `stats`. This will return a DOM object based on the the type of game and the stats.
    - [x] Create a function called `insertStats` with a single parameter `username`. This will make another XHR for the stats endpoint `https://api.chess.com/pub/player/$input_value/stats`.
      - [x] Clear any previous html elements that were in `stats` before you start renderering new stat entries to the table.
      - [x] Loop through this `xhr.response` and call `renderStats` and pass in each key-value pair inside the response that isn't the property `fide`. Make sure to append the result of each call to the `stats` HTML. 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
