### ISSUE TITLE
Feature: User can bookmark a game

### ISSUE THREAD

**Issue by eric-k-chu** [eric-k-chu/Castle#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can bookmark a game to view later

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When a user views a player's match history, there will be a bookmark icon in the entry. If a player clicks on it, the game will be saved to their bookmarks.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Bookmark icon under link icon when looking at a player's match history
![1](https://github.com/eric-k-chu/Castle/assets/47008060/0fe02ce6-294a-4ec5-b5c3-3f29e96b171a)

Modals
![Bookmark modal(1)](https://github.com/eric-k-chu/Castle/assets/47008060/8f642687-7be5-4070-86b1-58804f227e0d)
![Bookmark modal(2)](https://github.com/eric-k-chu/Castle/assets/47008060/dec20476-6eb1-41a3-a4f4-a684f8435b1e)

![Bookmarks](https://github.com/eric-k-chu/Castle/assets/47008060/31fcbbc0-2fc7-4079-a181-a31aeb5c9296)

![Desktop - Bookmarks](https://github.com/eric-k-chu/Castle/assets/47008060/d1535cbd-9b30-4f9e-be98-42ebe8319a35)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a new `nav-bar` item in for `Bookmarks`.
- [x] Create the HTML for the bookmarks view.
- [x] Add an event listener for the `Bookmarks` nav button that swaps to the bookmarks view.
- [x] Add a bookmarks property to `data`. This holds a map of DOM objects where the key is the bookmarkID and the value is the DOM object.
- [x] Add a bookmarkID property to `data`.
- [x] In the `renderMatch` function, in the root element for the match entry, add a data-id attribute and assign it `data.bookmarkID`. Then increment `data.bookmarkID`.
- [x] In the player match history section, add a bookmark icon under the link icon.
  - [x] Add an event listener to the parent element that holds the match entries.
  - [x] Upon clicking the bookmark icon, a modal should appear with a message indicating whether the game was saved or if the game already exists in your bookmarks. This should disappear after 1 second.
  - [x] Add the match entry that was clicked to `data.bookmarks`. 
  - [x] Add the match entry to the bookmarks list html.
- [x] In the bookmark section, add a trashcan icon under the link icon.
  - [x] Add an event listener to the parent element that holds the bookmark entries.
  - [x] Upon clicking the trashcan icon, delete the entry from the `data.bookmarks` as well as the bookmarks list html  
  - [x] A modal should appear with a message indicating that the entry was deleted.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
