### ISSUE TITLE
Feature: User's can select which game archives to view

### ISSUE THREAD

**Issue by eric-k-chu** [eric-k-chu/Castle#12]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to select a specific month + year and view the games played during that time.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

There will be a dropdown that displays month + year of the specific game archive. Users will be able to select an option and have those games be displayed.

## 🖼️ Wireframes

![ss](https://github.com/eric-k-chu/Castle/assets/47008060/09f188b2-b4bd-42d6-b4af-e7f3bf379132)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Set up local storage for the `data object`.
- [x] Change the display that shows the date of the archive to a `select` tag.
- [x] In the `getArchive` function, loop through `xhr.response` and add an `option` element to the select tag created earlier. The value for the option should be the date for each item in `xhr.response`. Then call `insertArchives` for the last endpoint in `xhr.response` since that will be default games shown.
- [x] Add an event listener for the select tag. Call `insertArchives` and pass in the selected value.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
