### ISSUE TITLE
Feature: User can view the daily puzzle

### ISSUE THREAD

**Issue by eric-k-chu** [eric-k-chu/Castle#14]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can view the daily puzzle for the day.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When user clicks on the `Daily Puzzle` navigation, a view will appear with the daily puzzle of the day. The user can click on the image
which will lead them to Chess.com where they can solve the daily puzzle.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Daily Puzzle](https://github.com/eric-k-chu/Castle/assets/47008060/3d6235f1-80de-41d3-b1b6-7542055197a1)
![Desktop - Daily Puzzle](https://github.com/eric-k-chu/Castle/assets/47008060/0d140711-f7d3-4f08-92dc-a2de62bd4c39)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the HTML for the `daily-puzzle` view
- [x] When the user clicks on the image link, it should open a new tab to where they can play the puzzle.
- [x] link the view to the `daily puzzle` nav item.
- [x] Add a new property called `dailyPuzzle` to `data` that holds an object containing information about the daily puzzle.
- [x] When the website loads, make an XHR `GET` request to https://api.chess.com/pub/puzzle and store that data into `dailyPuzzle`

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
