### ISSUE TITLE
Feature: User can view the list of tournaments the player has been in

### ISSUE THREAD

**Issue by eric-k-chu** [eric-k-chu/Castle#16]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to view the list of tournaments the player is registered, is attending or has attended in the past. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks on the tournaments tab, the user will see lists of finished, in progress, and registered tournaments

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Player Tournaments](https://github.com/eric-k-chu/Castle/assets/47008060/89fee652-cee4-4752-9972-6f59e64df2bd)
![Desktop - Player Tournaments(1)](https://github.com/eric-k-chu/Castle/assets/47008060/ed003be1-d7f2-407c-b3ba-1e313372b2b4)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the HTML for the `tab-bar` right under the `player-info-header`.
- [x] Create a tab for summary and tournaments
- [x] Add an eventlistener to `tab-bar` for the click event.
  - [x] If the event.target equals the selected tab, then make the selected tab highlighted
  - [x] Otherwise, make the others not highlighted.
- [x] Create the HTML for the `tournaments` tab-view.
- [x] Create a `currentPlayer` property for `data`. This will hold an object containing properties for the searched player's username, info, stats, clubs, gameArchive, and tournaments.
  - [x] In the functions where the endpoints for info, stats, clubs, and game archives are used, assign those `xhr.response` to the corresponding property of `data.currentPlayer`.
- [x] If the user clicks on the tournament tab and `data.currentPlayer.tournaments` does not exist,
  - [x] make an XHR GET to `https://api.chess.com/pub/player/${data.currentUsername}/tournaments` then swap to the tab.
  - [x] Otherwise, just swap to the tab.
- [x] For each item in all the tournament lists, display the name, placement, and points awarded.
  - [x] Get the name of the tournament from the @id property.
  - [x] Use the `split` method with the arguments '/' and 5 to isolate the name of the tourney.
  - [x] Use the 'split' method with '-', the filter method to remove "", and the join method to recreate the name.
- [x] Add three buttons, where each button will display the corresponding tournament list (finished, in progress, registered)
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
