### ISSUE TITLE
Feature: User can view all the clubs a player is currently in.

### ISSUE THREAD

**Issue by eric-k-chu** [eric-k-chu/Castle#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

users will be able to view all the clubs(up to 5) a player is currently in.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When a user successfully searches for a player, the player info page will appear with a list of the clubs (up to 5) a player is currently in.

## 🖼️ Wireframes

![Player Info and Stats](https://github.com/eric-k-chu/ajax-project/assets/47008060/f3e8cb87-65b7-4152-b931-52a3f5d38fe0)
![Desktop - Player Info and Stats](https://github.com/eric-k-chu/ajax-project/assets/47008060/b5f7d388-d49d-4916-afcf-1f9521e29e2c)

## ✅ Task List
- [x] Create a function called `renderClub` with a single parameter `club`. This returns a DOM object which will be appended to the `clubs` section.
- [x] Create a function called `insertClubs` with a single parameter `username`.
    - [x] Make another XHR for the clubs endpoint `https://api.chess.com/pub/player/$USERNAME/clubs`. This should return a list of endpoints to a specific list of games according to the month. 
    - [x] Clear any previous html elements that were in `clubs` before you start rendering new club entries to the table.
    - [x] Loop through this `xhr.response` and call `renderClub`  and pass in the up to the first 5 elements from the club list. Make sure to append the result of each call to the `clubs` table.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
