### ISSUE TITLE
 Feature: User can view the latest games a player played in.

### ISSUE THREAD

**Issue by eric-k-chu** [eric-k-chu/Castle#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Player Info and Stats(1)](https://github.com/eric-k-chu/Castle/assets/47008060/81d33719-d7df-4090-8c7f-9d949bd1412b)
![Info and Stats None](https://github.com/eric-k-chu/Castle/assets/47008060/5a52c71b-a4af-4b21-ac62-2b6663973694)

![Desktop - Player Info and Stats](https://github.com/eric-k-chu/Castle/assets/47008060/faf71c5c-8f14-4608-8d1c-36036929b58f)
![Desktop - Info and Stats None](https://github.com/eric-k-chu/Castle/assets/47008060/15fabed1-496a-45bb-97f8-08359fe0e4a2)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Create a function called `renderMatch` with a single parameter `game` which will return a DOM object of a specific match.
- [x] Create a function called `insertMatches` that takes in a single parameter `endpoint`.
  - [x] Make Make a `XMLHTTPRequest` to the `endpoint`.
  - [x] Loop through `xhr.response.games` starting from the end and call `renderMatch` for each element (max of 10)
  - [x] Append the result to the `match-history` element.
- [x] Create a function called `getArchive` that takes in a single parameter `username`. 
  - [x] Make a `XMLHTTPRequest` to the endpoint `https://api.chess.com/pub/player/${username}/games/archives`.
  - [x] In the event listener for the xhr object, clear any previous entries in the match history list.
  - [x] If the `xhr.response.archives` array is empty, create a DOM object that displays an error message in the `match-history` element.
  - [x] Otherwise, call `insertMatches` and pass in the last element of `xhr.response.archives`.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
