### ISSUE TITLE
Feature: User can view the leaderboard for the top 50 players in each game mode.

### ISSUE THREAD

**Issue by eric-k-chu** [eric-k-chu/Castle#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the leaderboards for the top 50 players in each game mode

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When user clicks on the `leaderboards` nav, a new page will appear that will show the leaderboards for the top 50 players in each game mode.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Leaderboards](https://github.com/eric-k-chu/Castle/assets/47008060/de725980-78e1-488d-a322-ddc45f3d3d46)
![Desktop - Leaderboard](https://github.com/eric-k-chu/Castle/assets/47008060/85bf9bda-3383-420b-9006-48d40f4484f6)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the HTML for the `leaderboards` view
- [x] Add an event listener to the leaderboards button that swaps to the `leaderboards` view and does the following:
  - [x] check if `data.leaderbaords` exists. If it doesn't, make an XHR `GET` for `https://api.chess.com/pub/leaderboards` and store the xhr.response in the `data` object as `leaderboards`.
  - [x] create the function called `renderLeaderboard` that takes in 1 parameter `index`. This should create DOM objects for every item in `leaderboards[index]`
  - [x] call `renderLeaderboard` and pass in `0`. This will be default leaderboard that appears when the `leaderboards` view is shown.
- [x] Add an event listener for the `select` menu in the leaderboards table.
  - [x] When a user selects an option, clear all the rows in the table body.
  - [x] call `renderLeaderboard` and pass in the option index.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
